### ISSUE TITLE
Type not found System.Int64

### ISSUE THREAD

**Issue by patcout26** [tomba/netserializer#73]
**Version NetSerializer 4.1.0**

I have a dictionary<string, object> and when i put long type i have this exception 
**Type not found System.Int64**

stacktrace:

 at NetSerializer.TypeDictionary.get_Item(Type key)
   at NetSerializer.Serializer.GetTypeIdAndSerializer(Type type, SerializeDelegate`1& del)
   at NetSerializer.ObjectSerializer.Serialize(Serializer serializer, Stream stream, Object ob)
   at Serialize(Serializer serializer, Stream stream, KeyValuePair`2 value)
   at Serialize(Serializer serializer, Stream stream, KeyValuePair`2[] value)
   at NetSerializer.ObjectSerializer.Serialize(Serializer serializer, Stream stream, Object ob)
   at NetSerializer.DictionarySerializer.WritePrimitive[TKey,TValue](Serializer serializer, Stream stream, Dictionary`2 value)
   at NetSerializer.ObjectSerializer.Serialize(Serializer serializer, Stream stream, Object ob)
   at Serialize(Serializer serializer, Stream stream, Inscription value)
   at NetSerializer.ObjectSerializer.Serialize(Serializer serializer, Stream stream, Object ob)
   at Serialize(Serializer serializer, Stream stream, KeyValuePair`2 value)
   at Serialize(Serializer serializer, Stream stream, KeyValuePair`2[] value)
   at NetSerializer.ObjectSerializer.Serialize(Serializer serializer, Stream stream, Object ob)
   at NetSerializer.DictionarySerializer.WritePrimitive[TKey,TValue](Serializer serializer, Stream stream, Dictionary`2 value)
   at NetSerializer.ObjectSerializer.Serialize(Serializer serializer, Stream stream, Object ob)
   at NetSerializer.ObjectSerializer.Serialize(Serializer serializer, Stream stream, Object ob)

**Comment by tomba** [comment]
Can you create a simple example that causes this? I can't reproduce.

**Comment by patcout26** [comment]
void Main()
{
	long n = 3;
	var test = new Test();
	test.Dict.Add("key1", "test");
	test.Dict.Add("key2", n);

	SerializeToStream(test);
}

private static MemoryStream SerializeToStream<T>(T objects) where T : class
{
	var ser = new Serializer(new[] { typeof(T) });
	var stream = new MemoryStream();
	ser.Serialize(stream, objects);

	return stream;
}

[Serializable]
public class Test
{
	public Test()
	{
		Dict = new Dictionary<string, object>();
	}

	public Dictionary<string, object> Dict { get; set; }
}

**Comment by patcout26** [comment]
> Can you create a simple example that causes this? I can't reproduce.

void Main()
{
long n = 3;
var test = new Test();
test.Dict.Add("key1", "test");
test.Dict.Add("key2", n);

SerializeToStream(test);
}

private static MemoryStream SerializeToStream(T objects) where T : class
{
var ser = new Serializer(new[] { typeof(T) });
var stream = new MemoryStream();
ser.Serialize(stream, objects);

return stream;
}

[Serializable]
public class Test
{
public Test()
{
Dict = new Dictionary<string, object>();
}

public Dictionary<string, object> Dict { get; set; }
}

**Comment by tomba** [comment]
Ah, right. I see.

NetSerializer needs to know all the types you will serialize beforehand. That is why you must pass it the list of types. It cannot know that you want to serialize an Int64. You have to provide that when instantiating the serializer.
